### ISSUE TITLE
Move production servers to new server room

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ku-migration#12]
Dependencies:
- [x] Server room network is set up, #1 
- [x] Everything backed up to the University system #8
- [x] Server room racks set up, #5 
- [x] Office systems no longer on GBIF infrastructure #11

---

Implementation:
- [x] Identify subset of servers to move
- [x] Document network requirements for them
- [x] Set up network in preparation
- [ ] Set up KVM in preparation
- [x] Take additional backup of servers where necessary
- [x] Announce downtime to GBIF staff

Moving day:
- [x] Make any necessary configuration changes to servers
- [x] Pause Nagios monitoring
- [x] Shut down servers
- [x] Check all expected services are still functioning!
- [x] Unrack, move and rerack servers in new room
- [x] Power up, test
- [x] Enable Nagios monitoring
