### ISSUE TITLE
Move away from Livelink

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ku-migration#15]
Dependencies:
- [x] Identify alternative document system #9 

---

Implementation:
- [x] Initial test export from Livelink
- [x] Make a full export of Livelink data and ask administration staff to verify it
- [x] Set up new system (whatever it may be)
- [x] Either move all at once, or move parts.  (If moving parts, the Livelink folders could be hidden from all staff to prevent updates)
- [x] Test and verify etc
- [ ] Celebrate :beers: :cocktail: :wine_glass: :fireworks: :sparkles:

**Comment by MattBlissett** [comment]
I have 99% of a full export from Livelink.

We have this many items:

| Count | Type | Exported |
| ------- | ------ | ------------ |
| 101805 |    Document | Export done, needs to be put somewhere for testing |
|    582 |    Text Document | Export done, etc.  |
|   8825 |    Email | Export done, etc. |
|   1552 |    Alias | Proper export would be tricky, destination system needs support anyway |
|     55 |    Link | To be exported as HTML |
|     24 |    News | Not intended for export |
|     19 |    Reply | Not intended for export |
|      1 |    Task | Not intended for export |
|     57 |    Topic | Not intended for export, dump if required |

### Aliases
These are symbolic links.  If the target supports them it's likely they could be exported, with some fiddling. It's easy to see where the links are, but not where they point to.

### Documents and text documents
These are fine.  About 200 aren't correctly put in the right place in the folder structure, they appear to have a suitable path, almost the right filename, but for some reason aren't in the XML export. I'll probably move them manually.

### Emails
These seem to be fine.

Depending on the target system, it could be worthwhile converting them from the Microsoft/Oracle format to a standard email format.

### Link
These are URLs, and could perhaps be exported as tiny HTML documents containing a link.

### News
These don't appear to hold any content, they are just tests.

### Topic, Reply
The topics hold email logs, which are mostly spam — including attachments, probably including viruses.  I don't think we should export this, but a compressed dump could be kept if needed.

There are a couple of tiny discussions other than email logs, but they appear mostly to be from testing.

### Task
If needed, export manually.

**Comment by MattBlissett** [comment]
Aliases and links are now exported.

**Comment by MattBlissett** [comment]
The top level folders from LiveLink can be exported individually, and marked read-only in LiveLink.

- [ ] Discussions
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] Documents
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] Finance
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] Governance and Collaborations
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] Governing Board and standing Committees
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] Human Resources
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] ICT
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] Management
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] New Director of GBIF
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] Participants
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] PR & Communications
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] Secretariat Administration
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] Strategy
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com
- [ ] Work Programme
  - [ ] Mark read-only in Livelink
  - [ ] Export from Livelink
  - [ ] Process (links etc)
  - [ ] Upload to box.com

**Comment by MattBlissett** [comment]
I was looking at backups of box.com.

One option is to mount using WebDAV, then use rsync. That's nicely understood by everyone, and with a couple of rsync options will give us incremental backups.  We will lose the 'created' time, file owner, permissions etc.  

Another option is the FTP sync. I assume it would also work, but it's much more obscure software than rsync. I prefer rsync.

The third option is a cloud provider. A couple exist, and might cost around $200/year.

I think WebDAV+rsync is the best option if we're backing up to a server we control, or a KU share.  If we're backing up to S3 or whatever, the cloud provider will avoid the more complicated set-up that we'd need.

**Comment by MattBlissett** [comment]
Using WebDAV to read *from* box.com seems to work OK, but using WebDAV to write *to* the KU share fails — perhaps it's too much data at once, but the local cache fills up, then never seems to clear.

I'll experiment with using rsync's rate-limiting option, otherwise we'll need to ask SIT for a better way.

**Comment by MattBlissett** [comment]
Rate limiting rsync didn't help.

I've set up a backup to Aino instead, running every 24 hours.

**Comment by MattBlissett** [comment]
I haven't marked everything read-only in Livelink, since it looks like it would override more restrictive permissions in subfolders.
